name: enthrix_messenger
description: A modern Flutter messenger app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  google_sign_in: ^6.2.1
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "icon.png"
